stages:
- deploy
- cleanup

sync to s3 mr:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - aws --endpoint-url $S3_ENDPOINT s3 sync . s3://"$S3_BUCKET/$CI_MERGE_REQUEST_IID" --delete --exclude ".git/*" --exclude "*.md" --exclude ".*" --exclude "*.json" --exclude "*.txt"
  only:
    refs:
      - merge_requests

clean merged s3 mr sync:
  stage: cleanup
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - echo "Cleaning up MR-${CI_MERGE_REQUEST_IID} directory"
    - aws --endpoint-url $S3_ENDPOINT s3 rm s3://"$S3_BUCKET/$CI_MERGE_REQUEST_IID --recursive"
  only:
    - merged

sync to s3 main:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - aws --endpoint-url $S3_ENDPOINT s3 sync . s3://"$S3_BUCKET/main" --delete --exclude ".git/*" --exclude "*.md" --exclude ".*" --exclude "*.json" --exclude "*.txt"
  only:
    refs:
      - main